### PR TITLE
Grammar improvmenents & resource links

### PR DESCRIPTION
**Pull request by dylanblanchard**
Hey @stabback
Thanks for putting this resource together. super rad.

I've gone through and suggested a couple of grammar changes that I hope improves the readability. I suspect a lot of the sentence structure is inhereited from the flowchart with minimal space, but there's some breathing room now.

I've also included a couple of links to resources to explain certain concepts (eg Snowball & Avalanche - lines 177 & 190). I think it'd be great to link to these resources so people can learn about them as they encounter them, but I don't know how to link shit in JS. 🤔

Thoughts?

### CODE REVIEW

**Comment by stabback** [comment]
Woah, unexpected PR!  Thanks for the help!

Linking - there's no support for links in the cards yet.  The store is going to eventually be moved over to Firebase, so there's enough of an architectural change there that things are flexible.

I was debating either storing the content of each step as HTML (supporting native `<a>` links) or enforcing content as plaintext and supporting linking as the little cards below.  This version of the site is definitely an MVP, so I'm OK with how you linked everything!

Thanks for the assistance!

**Comment by stabback** [comment]
@dylanblanchard Deployed, unsure how long AWS takes to update caches.  1 min to 1 hour?

**Comment by dylanblanchard** [comment]
Sweet! Unexpected PRs are the best.
I’ll keep an eye out for anything I can help with. I’m pretty garbage, but
can write haha

Thanks again for putting this together!

**Comment by stabback** [comment]
@dylanblanchard Very appreciated, content is _not_ my strong point.

**Pull request merged**
